version: "3"
services:
  database:
    image: postgres:17-alpine
    container_name: csu_database
    environment:
      POSTGRES_DB: "main"
      POSTGRES_USER: ${LOGIN}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - ./database:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    expose:
      - 5432
  app:
    container_name: csu_app
    build: ./app/
    env_file:
      - app/app/.env
    volumes:
      - ./dockerModel/hub:/root/.cache/huggingface/hub
    depends_on:
      - database
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  web-proxy:
    container_name: csu_web-proxy
    build: ./web-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - database
  rabbitmq:
    container_name: csu_rabbitmq
    image: rabbitmq:4-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${LOGIN}
      - RABBITMQ_DEFAULT_PASS=${PASSWORD}
    volumes:
      - .:/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    depends_on:
      - app
      - database
  telebot:
    container_name: csu_telebot
    build: ./telebot/
    env_file:
      - telebot/app/.env
    depends_on:
      - database