version: "3"
services:
  database:
    image: postgres:17-alpine
    container_name: csu_database
    environment:
      POSTGRES_DB: "main"
      POSTGRES_USER: ${LOGIN}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - ./database:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    expose:
      - 5432
  app:
    container_name: csu_app
    build: ./app/
    image: event-planner-api:lastest
    env_file:
      - app/.env
    volumes:
      - ./app:/app
    depends_on:
      - database
  web-proxy:
    container_name: csu_web-proxy
    build: ./web-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
  rabbitmq:
    container_name: csu_rabbitmq
    image: rabbitmq:4-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${LOGIN}
      - RABBITMQ_DEFAULT_PASS=${PASSWORD}
    volumes:
      - .:/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    depends_on:
      - app